config:
  ## The datasource properties on config are passed through helm tpl function.
  ## ref: https://helm.sh/docs/developing_charts/\#using-the-tpl-function
  datasource:
    # Specify one of both datasource or datasourceSecret
    host: "10.244.0.8"
    user: postgres
    password: abSwwNOoxg

serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  labels:
    release: my-kube-prometheus-stack
